language: java
jdk:
  - oraclejdk8
os: windows
  
env:
  - CODECOV_TOKEN='4672200f-2ce9-41dc-8f5b-7f4924fd413b'


before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)